//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IAPI")]
public interface IAPI
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPI/Query", ReplyAction="http://tempuri.org/IAPI/QueryResponse")]
    string Query(string mno);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPI/Query", ReplyAction="http://tempuri.org/IAPI/QueryResponse")]
    System.Threading.Tasks.Task<string> QueryAsync(string mno);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPI/PreSubmit", ReplyAction="http://tempuri.org/IAPI/PreSubmitResponse")]
    string PreSubmit(string act, string serial, string memo);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPI/PreSubmit", ReplyAction="http://tempuri.org/IAPI/PreSubmitResponse")]
    System.Threading.Tasks.Task<string> PreSubmitAsync(string act, string serial, string memo);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IAPIChannel : IAPI, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class APIClient : System.ServiceModel.ClientBase<IAPI>, IAPI
{
    
    public APIClient()
    {
    }
    
    public APIClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public APIClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public APIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public APIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string Query(string mno)
    {
        return base.Channel.Query(mno);
    }
    
    public System.Threading.Tasks.Task<string> QueryAsync(string mno)
    {
        return base.Channel.QueryAsync(mno);
    }
    
    public string PreSubmit(string act, string serial, string memo)
    {
        return base.Channel.PreSubmit(act, serial, memo);
    }
    
    public System.Threading.Tasks.Task<string> PreSubmitAsync(string act, string serial, string memo)
    {
        return base.Channel.PreSubmitAsync(act, serial, memo);
    }
}
